export const REQUEST_DESTINATION = 'REQUEST_DESTINATION'
export const GET_DESTINATION_FAILURE = 'GET_DESTINATION_FAILURE'
export const GET_DESTINATION_SUCCESS = 'GET_DESTINATION_SUCCESS'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'